# QR分解
分解要求：矩阵的列线性无关。
## 1.介绍
$\quad$如果$m\times n$矩阵$A$的列线性无关，那么$A$可以分解为$A=QR$，其中$Q$是一个$m\times n$矩阵，其列形成$ColA$的一个[标准正交基]，$R$是一个$n\times n$上三角可逆矩阵且在对角线上的元素为正数。$QR$分解常用于求解[特征值]以及[最小二乘求解]。  

<img src="./_image/17_1.png" width="650" height="350" />  

$\quad$对$m\times n$矩阵$A$做$QR$分解步骤如下：
* 对$A$的列向量应用[格拉姆-施密特方法]得到一组正交基，再单位化后得到单位正交基，单位正交基构成矩阵Q的列；
* 可知$Q^{T}Q=I$（正交矩阵的定理），所以有$Q^{T}A=Q^{T}QR=R$，因此计算$Q^{T}A$即可得到$R$。  

举一个例子：

<img src="./_image/17_2.png" width="650" height="350" />  

## 2.QR分解求特征值
$\quad$$QR$分解被广泛地用来估计一般矩阵$A$的特征值。算法流程如下：  
1. $A$被分解为$Q_{1},R_{1}$，计算$R_{1}Q_{1}$得到$A_{1}$；
2. $A_{1}$被分解为$Q_{2},R_{2}$，计算$R_{2}Q_{2}$得到$A_{2}$；  
3. 以此类推，计算到第$k$次时，$A_{k}$几乎是上三角的，且对角线上单元素近似于$A$的特征值。  

可以简单地证明，$A$是相似于$A_k$的：

<img src="./_image/17_3.png" width="650" height="350" />  

$\quad$用Python来实现该算法，取k=20或100来对比，$A=
\begin{bmatrix}
   2 & 3\\
   3 & -6
  \end{bmatrix}$，代码如下所示：

In [1]:
import numpy as np  
from scipy.linalg import eig  
from scipy.linalg import qr  
def qr_eig(A, times):  
    for i in range(times):  
        q, r = qr(A)  
        A = np.dot(r, q)  
    return A  
  
if __name__ == "__main__":  
  
    mat = np.asarray([[2, 3], [3, -6]])  
    eigenvalues, eigenvectors = eig(mat)  
    print('without using qr, the eigenvalues is \n%s'%eigenvalues)  
    print('without using qr, the eigenvectors is \n%s\n'%eigenvectors)  
  
    times = 20  
    mat = qr_eig(mat, times)  
    print('after %d qr, the mat is \n%s'%(times, mat))  
    eigenvalues, eigenvectors = eig(mat)  
    print('after using qr, the eigenvalues is \n%s'%eigenvalues)  
    print('after using qr, the eigenvectors is \n%s\n'%eigenvectors)  
  
    times = 100  
    mat = qr_eig(mat, times)  
    print('after %d qr, the mat is \n%s' % (times, mat))  
    eigenvalues, eigenvectors = eig(mat)  
    print('after using qr, the eigenvalues is \n%s' % eigenvalues)  
    print('after using qr, the eigenvectors is \n%s\n' % eigenvectors) 

without using qr, the eigenvalues is 
[ 3.+0.j -7.+0.j]
without using qr, the eigenvectors is 
[[ 0.9486833  -0.31622777]
 [ 0.31622777  0.9486833 ]]

after 20 qr, the mat is 
[[-7.00000000e+00  1.31094825e-06]
 [ 1.31094825e-06  3.00000000e+00]]
after using qr, the eigenvalues is 
[-7.+0.j  3.+0.j]
after using qr, the eigenvectors is 
[[-1.00000000e+00 -1.31094825e-07]
 [ 1.31094825e-07 -1.00000000e+00]]

after 100 qr, the mat is 
[[-7.00000000e+00 -1.41631858e-15]
 [ 2.08884887e-43  3.00000000e+00]]
after using qr, the eigenvalues is 
[-7.+0.j  3.+0.j]
after using qr, the eigenvectors is 
[[ 1.00000000e+00 -1.41631858e-16]
 [ 0.00000000e+00  1.00000000e+00]]



k=100与k=20相比，通过$QR$分解计算出来的矩阵除对角线外元素更趋于0；通过$QR$分解计算得到的矩阵对角线上元素均趋于特征值。