# Python Learning

## 1.求绝对值

In [1]:
abs(-6)

6

# 2.元素都为真
接受一个迭代器，如果迭代器的说要元素都为真，要么返回True，要么返回False

In [2]:
all([1, 0, 3, 6])

False

In [3]:
all([1, 2, 3])

True

## 3.元素至少存在一个为真
接受一个迭代器，如果迭代器里至少存在一个元素为真，要么都返回True，否则都返回False

In [4]:
any([0, 0, 0, []])

False

In [5]:
any([0, 0, 1])

True

## 4.ascii展示对象
调用对象的repr()方法, 获得该方法的返回值, 下面返回值为字符串

In [6]:
class Student():
    def __init__(self, id, name):
        self.id = id
        self.name = name

    def __repr__(self):
        return 'id = ' + self.id + ', name = ' + self.name

In [7]:
# 创建对象实例，小明
xiaoming = Student(id = '001', name = 'xiaoming')

In [8]:
ascii(xiaoming)

'id = 001, name = xiaoming'

## 5.十进二
将十进制转换为二进制

In [9]:
bin(10)

'0b1010'

## 6.十进八
将十进制转换为八进制

In [10]:
oct(9)

'0o11'

## 7.十进十六
将十进制转换为十六进制

In [11]:
hex(15)

'0xf'

## 8.判断真假
测试一个对象是True，还是False

In [12]:
bool([0, 0, 0])

True

In [13]:
bool([])

False

In [14]:
bool([1, 0, 1])

True

## 9.字符串转字节
将一个字符串转换为字节类型

In [15]:
s = "apple"
bytes(s, encoding='utf-8')

b'apple'

## 10.转为字符串
将字符类型、数值类型等转换为字符串类型

In [16]:
i = 100
str(i)

'100'

## 11.是否可调用
判断对象是否可调用，能被调用的对象就是一个callable对象，比如函数str, int 等都是可被调用的，但是列子4中xiaoming实例不可调用的。

In [17]:
callable(str)

True

In [18]:
callable(int)

True

In [19]:
xiaoming

id = 001, name = xiaoming

In [20]:
callable(xiaoming)

False

In [21]:
# 如果想让xiaoming能被调用xiaoming()，需要重新写一个Student类的__call__方法
class Student():
    def __init__(self, id, name):
        self.id = id
        self.name = name

    def __repr__(self):
        return 'id = ' + self.id + ', name = ' + self.name

    def __call__(self):
        print("I can be called")
        print(f'my name is {self.name}')

# 创建小明实例
t = Student('001', xiaoming)


In [22]:
t()

I can be called
my name is id = 001, name = xiaoming


## 12.十转ASCII
查看十进制整数对应的ASCII字符

In [23]:
chr(65)

'A'

## 13.ASCII转十
查看某个ASCII字符对应的十进制数

In [24]:
ord('A')

65

## 14.类方法
classmethod装饰器对应的函数不需要实例化，不需要self参数，但是第一个参数需要是表示自身类的cls参数，可以用来调用类的属性，类的方法，实例化对象等

In [25]:
class Student():
    def __init__(self, id, name):
        self.id = id
        self.name = name

    def __repr__(self):
        return 'id = ' + self.id + ', name = ' + self.name
    
    @classmethod
    def f(cls):
        print(cls)

## 15.字符串表示的代码
将字符串编译成python能识别或可执行的代码，也可将文字读成字符串在编译

In [26]:
s = 'print("hello world")'
r = compile(s, "<string>", "exec")
print(r)

<code object <module> at 0x0000016AB6BA20E0, file "<string>", line 1>


In [27]:
exec(r)

hello world


## 16.创建复数
创建一个复数

In [28]:
complex(1, 2)

(1+2j)

## 17.动态删除属性
删除对象的属性

In [29]:
delattr(xiaoming, 'id')

In [30]:
hasattr(xiaoming, 'id')

False

## 18.转换字典
创建数据字典

In [31]:
dict()

{}

In [32]:
dict(a = 'a', b = 'b')

{'a': 'a', 'b': 'b'}

In [33]:
dict(zip(['a', 'b'], [1, 2]))

{'a': 1, 'b': 2}

In [34]:
dict([('a', 1), ('b', 2)])

{'a': 1, 'b': 2}

## 19.查看对象所有方法
一键查看对象中所有的方法，不带参数时返回当前范围内的变量、方法和定义的类型列表，带参数时返回参数的属性，方法列表

In [35]:
dir(xiaoming)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'name']

## 20.取商和余数
分别取商和余数

In [36]:
divmod(10, 3)

(3, 1)

## 21.枚举对象
返回一个可以美剧的对象，该对象的next()方法将返回一个元组

In [37]:
s = ["a", "b", "c"]
for i, v in enumerate(s, 1):
    print(i, v)

1 a
2 b
3 c


## 22.计算表达式
将字符串str当成有效的表达式来取值并返回计算结果取出字符串的内容

In [38]:
s = "1 + 3 + 5"
eval(s)

9

## 23.查看占用内存
查看变量所占字节数

In [39]:
import sys

a = {'a': 1, 'b': 2.0}

sys.getsizeof(a) # 占用232字节

232

## 24.过滤器
在函数中设定过滤条件，迭代元素，保留返回值为True的元素

In [40]:
fil = filter(lambda x: x > 10, [1, 11, 2, 45, 7, 6, 13])
list(fil)

[11, 45, 13]

## 25.转换浮点类型
将一个整数或数值型。字符串转换为浮点数

In [41]:
float(3)

3.0

## 26.字符串格式化
格式化输出字符串：format(value, format_spec)实际上时调用了value的format(format_spec)方法

## 27.冻结集合
创建一个不可修改的集合

In [42]:
# 因为不可修改，所以没有像set那样的add和pop方法
frozenset([1, 1, 3, 2, 3])

frozenset({1, 2, 3})

In [43]:
frozenset([1, 2, 3])

frozenset({1, 2, 3})

## 28.动态获取对象属性
获取对象的属性

In [44]:
class Student():
    def __init__(self, id, name):
        self.id = id
        self.name = name

    def __repr__(self):
        return 'id = ' + self.id + ', name = ' + self.name

# 实例化对象
xiaoming = Student(id = '001', name = 'xiaoming')

In [45]:
# 获取xiaoming这个实例的name属性值
getattr(xiaoming, 'name') 

'xiaoming'

## 29.判断对象属性

In [46]:
class Student():
    def __init__(self, id, name):
        self.id = id
        self.name = name

    def __repr__(self):
        return 'id = ' + self.id + ', name = ' + self.name

# 实例化对象
xiaoming = Student(id = '001', name = 'xiaoming')

In [47]:
hasattr(xiaoming, 'name')

True

In [48]:
hasattr(xiaoming, 'address')

False

## 30.返回对象的哈希值
返回对象的哈希值，值得注意的是自定义的实例都是可哈希的， list, dict, set等都是可变对象都是不可哈希的(unhashable)

In [49]:
hash(xiaoming)

97365457785

In [50]:
hash([1, 2, 3])

TypeError: unhashable type: 'list'

## 31.一键帮助
返回对象的帮助文档

In [ ]:
help(xiaoming)

Help on Student in module __main__ object:

class Student(builtins.object)
 |  Student(id, name)
 |  
 |  Methods defined here:
 |  
 |  __init__(self, id, name)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |  
 |  __repr__(self)
 |      Return repr(self).
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance variables (if defined)
 |  
 |  __weakref__
 |      list of weak references to the object (if defined)



## 32.对象门牌号
返回对象的内存地址

In [ ]:
id(xiaoming)

1718870603040

## 33.获取用户输入
获取用户输入的内容

In [ ]:
a = input()

## 34.转换为整型
int(x, base = 10)， x可能为字符串或数值，将x转换一个普通整数。如果参数是字符串，那么它可能包含符号和小数点。入宫超出了普通整数的表示范围，一个长整数被返回。

In [ ]:
int('12', 16)

18

In [ ]:
int('2', 16)

2

## 35.isinstance
判断object是否为类classinfo的实例，是返回True

In [ ]:
class Student():
    def __init__(self, id, name):
        self.id = id
        self.name = name

    def __repr__(self):
        return 'id = ' + self.id + ', name = ' + self.name

# 实例化对象
xiaoming = Student(id = '001', name = 'xiaoming')

In [ ]:
isinstance(xiaoming, Student)

True

## 36.父子关系鉴定

In [ ]:
class undergraduate(Student):
    def studyClass(self):
        pass

    def attendActivity(self):
        pass

In [ ]:
issubclass(undergraduate, Student)

True

In [ ]:
issubclass(object, Student)

False

In [ ]:
issubclass(Student, object)

True

In [ ]:
# 如果class是classinfo元组中某一个元素的子类，也会返回True
issubclass(int, (int, float))

True

## 37.创建迭代器类型
使用iter(obj, sentinel)，返回一个可迭代对象， Sentinel可省略(一旦迭代到此元素，立即终止)

In [ ]:
lst = [1, 3, 5]
for i in iter(lst):
    print(i)

1
3
5


In [ ]:
# 测试迭代器类的运用
class TestIter(object):
    def __init__(self):
        self.l = [1, 3, 2, 3, 4, 5]
        self.i = iter(self.l)

    def __call__(self):
        """
        定义__call__方法的类的实例是可调用的
        """
        
        item = next(self.i)
        print ("__call__ is called,fowhich would return",item)

        return item

    def __iter__(self):
        """
        支持迭代协议(即定义有__iter__()函数)
        """

        print ("__iter__ is called!!")

        return iter(self.l)

# 实例化对象
t = TestIter()

In [ ]:
# 因为实现了__call__方法，所所以t实例能被调用
t()

__call__ is called,fowhich would return 1


1

In [ ]:
# 因为实现了__iter__方法, 所有t能被迭代
for i in TestIter():
    print(i)

__iter__ is called!!
1
3
2
3
4
5


## 38.基类(根类)
object是所有类的基类

In [ ]:
o = object()

In [ ]:
type(o)

object

In [ ]:
object

object

## 39.文件
返回文件对象

In [ ]:
fo = open('D:/a.txt', mode = 'r', encoding='urf-8')
fo.read()

## 40.次幂
base为底的exp次幂，如果mod给出，取余

In [ ]:
pow(3, 2, 4)

1

## 41.打印

In [ ]:
lst = [1, 3, 5]


In [ ]:
print(lst)

[1, 3, 5]


In [ ]:
print(f'lst: {lst}')

lst: [1, 3, 5]


In [ ]:
print('lst: ', lst)

lst:  [1, 3, 5]


## 42.创建属性的两种方式
返回property属性，典型的用法

In [ ]:
class C:
    def __init__(self):
        self._x = None

    def getx(self):
        return self._x

    def setx(self, value):
        self._x = value

    def delx(self):
        del self._x

    # 使用porperty类创建property属性
    x = property(getx, setx, delx, "I'm the 'x' property.") 

In [ ]:
# 使用python装饰器，实现与上完全一样效果代码
class C:
    def __init__(self):
        self._x = None

    @property
    def x(self):
        return self._x

    @x.setter
    def x(self, value):
        self._x = value 
    
    @x.deleter
    def x(self):
        del self._x

## 43.创建range()序列
1.range(stop)
2.range(start, stop[, stop])

In [ ]:
# 生成一个不可变序列
range(11)

range(0, 11)

In [ ]:
range(0, 11, 1)

range(0, 11)

## 44.反向迭代器

In [ ]:
rev = reversed([1, 4, 2, 3, 1])

In [ ]:
for i in rev:
    print(i)

1
3
2
4
1


## 45.四舍五入
四舍五入，ndigits代表小数点后保留几位

In [ ]:
round(10.0222222, ndigits=3)

10.022

In [ ]:
round(10.0222222, 3)

10.022

## 46.转为集合类型
返回一个set对象，集合内不允许存在重复元素

In [ ]:
a = [1, 4, 2, 3, 1]
set(a)

{1, 2, 3, 4}

## 47.转换切片对象
class slice(start, stop[, step])
返回一个表示由range(start, stop, step)所指定索引集的slice对象，它让代码可读性，可维护性好

In [ ]:
a = [1, 4, 2, 3, 1]
my_slice_meaning = slice(0, 5, 2)

In [ ]:
a[my_slice_meaning]

[1, 2, 1]

## 48.排序函数

In [ ]:
a = [1, 4, 2, 3, 1]
sorted(a, reverse = True)


[4, 3, 2, 1, 1]

In [ ]:
a = [{'name':'xiaoming','age':18,'gender':'male'},{'name':'xiaohong','age':20,'gender':'female'}]


In [ ]:
sorted(a,key=lambda x: x['age'],reverse=False)

[{'name': 'xiaoming', 'age': 18, 'gender': 'male'},
 {'name': 'xiaohong', 'age': 20, 'gender': 'female'}]

## 49.求和函数

In [ ]:
a = [1, 4, 2, 3, 1]
sum(a)

11

In [ ]:
sum(a, 10) # 求和的初始值为10 a = 10

21

## 50.转元组
tuple()将对象转为一个不可变的序列类型

In [ ]:
i_am_list =[1, 3, 5]
i_am_tuple = tuple(i_am_list)
i_am_tuple

(1, 3, 5)

In [ ]:
deck = []
for i in range(3, 15):
    deck.extend([i for _ in range(4)])
print(deck)

[3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9, 10, 10, 10, 10, 11, 11, 11, 11, 12, 12, 12, 12, 13, 13, 13, 13, 14, 14, 14, 14]


In [ ]:
deck.extend([17 for _ in range(4)])
print(deck)

[3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9, 10, 10, 10, 10, 11, 11, 11, 11, 12, 12, 12, 12, 13, 13, 13, 13, 14, 14, 14, 14, 17, 17, 17, 17]


In [ ]:
deck.extend([20, 30])
print(deck)

[3, 3, 3, 3, 4, 4, 4, 4, 5, 5, 5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9, 10, 10, 10, 10, 11, 11, 11, 11, 12, 12, 12, 12, 13, 13, 13, 13, 14, 14, 14, 14, 17, 17, 17, 17, 20, 30, 20, 30]


In [ ]:
a = 1
assert a>0
print(a)

1


In [ ]:
import numpy as np
matrix = np.zeros([4, 13,], dtype = np.int8)
print(matrix)

[[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]]


## 51.查看对象类型
class rtpe(name, bases, dict)
传入一个参数时，返回object的类型

In [ ]:
class Student():
    def __init__(self, id, name):
        self.id = id   
        self.name = name 

    def __repr__(self):
        return 'id = ' + self.id + ', name = ' + self.name

In [ ]:
xiaoming = Student(id = '001', name = 'xiaoming')
type(xiaoming)

__main__.Student

In [ ]:
type(tuple())

tuple

## 52.聚合迭代器
创建一个聚合来自每个可迭代对象中的元素的迭代器

In [ ]:
x = [3, 2, 1]
y = [4, 5, 6]
z = zip(y,x)

In [ ]:
print(z)

## 53.nonlocal内嵌函数
关键字nonlocal常用于函数嵌套中，声明便i为非局部变量，如果不声明， i += 1表明i为函数wrapper内的局部变量，因为 i += 1引用(reference)时，i未被声明，索引会报unreferenced variable的错误。

In [ ]:
from time import time


def excepter(f):
    i = 0
    t1 = time.time()

    def wrapper():
        try:
            f()
        except Exception as e:
            nonlocal i
            print(f'{e.args[0]}:{i}')
            t2 = time.time()

        if i == n:
            print(f'spending time:{round(t2-t1,2)}')
            
    return wrapper

## 54.global声明全局变量
global：一个变量被多个函数引用，想要让全局变量被说要函数共享。

In [ ]:
i = 5

def f():
    print(i)

def g():
    print(i)
    pass 

f()
g()

# f和g两个函数都唔那个共享变量i，程序不存在报错，所以它们依然不明白为什么使用global
# 但是，如果想要有个函数能对i进行递增
def h():
    i += 1

h()

# 此时执行程序，bang出错了，抛出异常：unboundLocalError，原来编译器在解释i += 1时
# 会把 i 解析为函数 h()内的局部变量，很显然在此函数内，编译器找不到变量i的定义，所以会报错。
#  global就额是解决此类问题而被提出，在函数h内，显然地告诉编译器i为全局变量，然会编译器会在
# 函数外寻找i的定义，所以执行完 i += 1后， i还未全局变量， 值加1
i = 0

def h1():
    global i    
    i += 1 

h()
print(i)


## 55.链式比较


In [ ]:
i = 3
print(1 < i < 3)

False


In [ ]:
print(1 < i <= 3)

True


## 56.不使用else和if实现计算器

In [ ]:
from operator import *

def calculator(a, b, k):
    return {
        '+': add,
        '-': sub,
        '*': mul,
        '/': truediv,
        '**': pow
    }[k](a, b)

In [ ]:
calculator(1, 2, '+')

3

In [ ]:
calculator(2, 18, '**')

262144

## 57.链式操作


In [ ]:
from operator import (add, sub)

def add_or_sub(a, b, oper):
    return (add if oper == '+' else sub)(a, b)


In [ ]:
add_or_sub(10, 100, '+')

110

## 58.交换两元素

In [ ]:
def swap(a, b):
    return b, a

print(swap(1, 0))

(0, 1)


## 59.去最求平均

In [ ]:
def score_mean(lst):
    lst.sort()
    lst2 = lst[1:(len(lst) - 1)]

    return round((sum(lst) / len(lst2)), 1)

lst=[9.1, 9.0,8.1, 9.7, 19,8.2, 8.6,9.8]
score_mean(lst)

13.6

## 60.打印九九

打印图下格式的乘法表


In [ ]:
1*1=1
1*2=2 2*2=4
1*3=3 2*3=6 3*3=9
1*4=4 2*4=8 3*4=12 4*4=16
1*5=5 2*5=10 3*5=15 4*5=20 5*5=25
1*6=6 2*6=12 3*6=18 4*6=24 5*6=30 6*6=36
1*7=7 2*7=14 3*7=21 4*7=28 5*7=35 6*7=42 7*7=49
1*8=8 2*8=16 3*8=24 4*8=32 5*8=40 6*8=48 7*8=56 8*8=64
1*9=9 2*9=18 3*9=27 4*9=36 5*9=45 6*9=54 7*9=63 8*9=72 9*9=81

In [ ]:
# 一共10行，第i行的第j列等于： j * i
# 其中
# i 取值范围： 1<=i<=9
# j 取值范围： 1<=j<=i
# 根据 例子分析 的语言描述，转化为如下代码：
for i in range(1, 10):
    for j in range(1, i + 1):
        print('%d*%d=%d'%(j,i,j*i),end="\t")
    print()

1*1=1	
1*2=2	2*2=4	
1*3=3	2*3=6	3*3=9	
1*4=4	2*4=8	3*4=12	4*4=16	
1*5=5	2*5=10	3*5=15	4*5=20	5*5=25	
1*6=6	2*6=12	3*6=18	4*6=24	5*6=30	6*6=36	
1*7=7	2*7=14	3*7=21	4*7=28	5*7=35	6*7=42	7*7=49	
1*8=8	2*8=16	3*8=24	4*8=32	5*8=40	6*8=48	7*8=56	8*8=64	
1*9=9	2*9=18	3*9=27	4*9=36	5*9=45	6*9=54	7*9=63	8*9=72	9*9=81	


In [ ]:
import numpy as np           

a = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])

In [ ]:
print(a[::-1])

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [ ]:
import numpy as np           

a = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
print(a[:, ::-1])

[[5 4 3 2 1]
 [5 4 3 2 1]]
